'use client';
import { useAtom } from 'jotai';
import { menuOpenAtom } from '@/store/atoms';

export default function HowItWorksPage() {
  const [menuOpen] = useAtom(menuOpenAtom);

  return (
    <div className={`max-w-5xl min-h-screen mx-auto px-6 py-12 ${menuOpen ? "hidden" : ""} bg-[#faf6f6] dark:bg-[#0a0a0a] mb-10`}>
      <h1 className="text-3xl md:text-5xl font-bold mb-12 text-center text-neutral-800 dark:text-white">
        How It Works
      </h1>

      <div className="grid gap-10 md:gap-14 text-base md:text-lg leading-relaxed">
        {/* Step 1 */}
        <section className="bg-white dark:bg-neutral-900 rounded-xl shadow-md dark:shadow-none p-6 md:p-8 border border-neutral-200 dark:border-neutral-800">
          <h2 className="text-xl md:text-2xl font-semibold mb-3 text-neutral-800 dark:text-white">1. Upload or Paste Your Resume</h2>
          <p className="text-neutral-700 dark:text-neutral-300">
            You can paste your resume directly into the form or upload a PDF file. This allows our system to extract and analyze your skills, experience, and qualifications.
          </p>
        </section>

        {/* Step 2 */}
        <section className="bg-white dark:bg-neutral-900 rounded-xl shadow-md dark:shadow-none p-6 md:p-8 border border-neutral-200 dark:border-neutral-800">
          <h2 className="text-xl md:text-2xl font-semibold mb-3 text-neutral-800 dark:text-white">2. Provide a Job Description</h2>
          <p className="text-neutral-700 dark:text-neutral-300">
            Paste the job description of the role you are applying to. Our AI compares your resume with the job requirements to determine compatibility and relevance.
          </p>
        </section>

        {/* Step 3 - Industry Selection */}
        <section className="bg-white dark:bg-neutral-900 rounded-xl shadow-md dark:shadow-none p-6 md:p-8 border border-neutral-200 dark:border-neutral-800">
          <h2 className="text-xl md:text-2xl font-semibold mb-3 text-neutral-800 dark:text-white">3. Select or Enter Your Industry</h2>
          <p className="text-neutral-700 dark:text-neutral-300">
            Choose your industry from a list of common sectors like Tech, Finance, Healthcare, etc., or type in a custom one. This helps the AI tailor its evaluation to context-specific expectations and terminology.
          </p>
        </section>

        {/* Step 4 */}
        <section className="bg-white dark:bg-neutral-900 rounded-xl shadow-md dark:shadow-none p-6 md:p-8 border border-neutral-200 dark:border-neutral-800">
          <h2 className="text-xl md:text-2xl font-semibold mb-3 text-neutral-800 dark:text-white">4. Get AI-Powered Fit Score & Feedback</h2>
          <p className="text-neutral-700 dark:text-neutral-300">
            Instantly receive a match score along with detailed insights on strengths, gaps, and suggestions — plus a summary — all generated by AI to help you improve your application.
          </p>
        </section>

        {/* Benefits Section */}
        <section className="bg-gradient-to-br from-pink-100 to-pink-200 dark:from-pink-900 dark:to-pink-800 rounded-xl p-6 md:p-8 shadow-md border border-pink-300 dark:border-pink-700">
          <h2 className="text-xl md:text-2xl font-semibold mb-4 text-pink-700 dark:text-pink-200">Why Use Our Tool?</h2>
          <ul className="list-disc pl-6 space-y-2 text-neutral-700 dark:text-neutral-200">
            <li>Save time — no more guessing what to improve in your resume.</li>
            <li>Get clear, tailored feedback for each job application.</li>
            <li>Boost your chances with data-driven insights into your fit.</li>
          </ul>
        </section>
      </div>
    </div>
  );
}
